spring:
  application:
    name: order-processing-service

# Custom MongoDB configuration
mongodbDatabase: exampleDb
mongodbUri: "mongodb://127.0.0.1:27017"

# WebFlux server configuration
apiPort: 9898

# gRPC server configuration
grpc:
  server:
    port: 9090

# SMPP configuration
smpp:
  host: localhost
  port: 2775
  systemId: testuser
  password: testpass
  systemType: ""
  sourceAddress: "1234"
  sourceAddressTon: 1
  sourceAddressNpi: 1
  destAddressTon: 1
  destAddressNpi: 1
  requestExpiryTimeout: 30000
  windowMonitorInterval: 15000
  windowSize: 1
  connectTimeout: 10000
  bindTimeout: 5000
  enabled: true


# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# Info endpoint
info:
  app:
    name: Order Processing Service
    description: Hacom Telecom Order Processing Service
    version: 0.0.1-SNAPSHOT
